Prefer short-circuiting guards to ifs.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,24 +9,20 @@ echo "Info: BUILD_DIR=$BUILD_DIR"
 CACHE_DIR=$2
 echo "Info: CACHE_DIR=$CACHE_DIR"
 
-[ -z $SQUEAK_VERSION ] && echo "Error: please set SQUEAK_VERSION in environment" && exit 1
+[ -z ${SQUEAK_VERSION} ] && echo "Error: please set SQUEAK_VERSION in environment" && exit 1
+[ -z ${BUILDPACK_SQUEAK_BASE_URL} ] && echo "Error: please set BUILDPACK_SQUEAK_BASE_URL" && exit 1;
 
-if [ -z ${BUILDPACK_SQUEAK_BASE_URL} ]; then
-    echo "Error: please set BUILDPACK_SQUEAK_BASE_URL";
-    exit 1;
-else
-    MAJOR_VERSION=`echo ${SQUEAK_VERSION} | cut -d"-" -f1`
+MAJOR_VERSION=`echo ${SQUEAK_VERSION} | cut -d"-" -f1`
 
-    mkdir -p ${CACHE_DIR}
-    (cd ${CACHE_DIR} && \
-	URL=${BUILDPACK_SQUEAK_BASE_URL}/${MAJOR_VERSION}/Squeak${SQUEAK_VERSION}.zip && \
-	echo "Info: Downloading ${URL}" && \
-	curl -O ${URL} && \
-	unzip -o Squeak${SQUEAK_VERSION}.zip && \
-	VMURL=${BUILDPACK_SQUEAK_BASE_URL}/${MAJOR_VERSION}/unix-linux/coglinux.tgz && \
-	echo "Info: Downloading ${VMURL}" && \
-	curl -O ${VMURL} && \
-	tar zxf coglinux.tgz &&
-	echo "Right now, Smalltalk has no 'cabal update' equivalent" && exit 0
-    )
-fi
+mkdir -p ${CACHE_DIR}
+(cd ${CACHE_DIR} && \
+    URL=${BUILDPACK_SQUEAK_BASE_URL}/${MAJOR_VERSION}/Squeak${SQUEAK_VERSION}.zip && \
+    echo "Info: Downloading ${URL}" && \
+    curl -O ${URL} && \
+    unzip -o Squeak${SQUEAK_VERSION}.zip && \
+    VMURL=${BUILDPACK_SQUEAK_BASE_URL}/${MAJOR_VERSION}/unix-linux/coglinux.tgz && \
+    echo "Info: Downloading ${VMURL}" && \
+    curl -O ${VMURL} && \
+    tar zxf coglinux.tgz &&
+    echo "Right now, Smalltalk has no 'cabal update' equivalent" && exit 0
+)
